import Head from "next/head";
import styles from "../styles/Home.module.css";
import useExpense from "../hooks/useExpense.ts";
import Torrents from "../components/Torrents.tsx";
import Footer from "../components/Footer.tsx";
import { Spinner } from "@chakra-ui/react";
import NewExpense from "../components/NewExpense.tsx";
import ExpenseTable from "../components/ExpensesTotalsTable.tsx";

export default function Expenses() {
  const {
    expenses,
    categoryGroupExpenses,
    loading,
    createExpenseHandler,
    creatingExpense,
  } = useExpense();

  return (
    <div className={styles.container}>
      <Head>
        <title>Expenses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading && (
          <>
            <Spinner /> Cargando... Espere!
          </>
        )}
        {!loading && (
          <>
            <NewExpense
              onCreate={createExpenseHandler}
              loading={creatingExpense}
            />
            <ExpenseTable expensesResult={categoryGroupExpenses} />
          </>
        )}
      </main>

      <Footer />
    </div>
  );
}
