import Head from "next/head";
import styles from "../styles/Home.module.css";
import useExpense from "../hooks/useExpense.ts";
import ExpenseTable from "../components/ExpensesTotalsTable.tsx";
import { Spinner } from "@chakra-ui/react";
import NewExpense from "../components/NewExpense.tsx";
import Torrents from "../components/Torrents.tsx";
import {
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
} from "@chakra-ui/react";
import { Box } from "@chakra-ui/react";

export default function Home() {
  const {
    expenses,
    categoryGroupExpenses,
    loading,
    createExpenseHandler,
    creatingExpense,
  } = useExpense();

  //const [selectedExpense, setSelected] = useState(null);
  //const categoryNames = Object.keys(categoryGroupExpenses);

  return (
    <div className={styles.container}>
      <Head>
        <title>Expenses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Accordion defaultIndex={[0]} allowMultiple w="100%">
          <AccordionItem>
            <h2>
              <AccordionButton>
                <Box as="span" flex="1" textAlign="left">
                  Torrents:
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              <Torrents />
            </AccordionPanel>
          </AccordionItem>

          <AccordionItem>
            <h2>
              <AccordionButton>
                <Box as="span" flex="1" textAlign="left">
                  Expenses:
                </Box>
                <AccordionIcon />
              </AccordionButton>
            </h2>
            <AccordionPanel pb={4}>
              {loading && (
                <>
                  <Spinner /> Cargando... Espere!
                </>
              )}
              {!loading && (
                <>
                  <NewExpense
                    onCreate={createExpenseHandler}
                    loading={creatingExpense}
                  />
                  <ExpenseTable expensesResult={categoryGroupExpenses} />
                </>
              )}
            </AccordionPanel>
          </AccordionItem>
        </Accordion>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>K2600X - garantía de algo...</span>
        </a>
      </footer>
    </div>
  );
}
