import Head from "next/head";
import styles from "../styles/Home.module.css";
import useExpense from "../hooks/useExpense.ts";
import Torrents from "../components/Torrents.tsx";
import Footer from "../components/Footer.tsx";

export default function TorrentsHome() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Torrents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Torrents />
      </main>

      <Footer />
    </div>
  );
}
